package Unidad_3;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author GuillermoToledano
 */
public class P08_JFileChooser extends JFrame {

    /**
     * Creates new form P08_JFileChooser
     */
    File f;
    int step;
    File path;
    String currDir = ".";

    int count;
    P08_Estudiante[] stds;

    public P08_JFileChooser() {
        looknfeel();
        initComponents();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("GPO", "gpo");
        FileChooser.addChoosableFileFilter(filter);
        FileChooser.setFileFilter(filter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        FileChooser = new javax.swing.JFileChooser();
        buttonGroup01 = new javax.swing.ButtonGroup();
        Panel01 = new javax.swing.JPanel();
        Panel02 = new javax.swing.JPanel();
        Label01 = new javax.swing.JLabel();
        TextField01 = new javax.swing.JTextField();
        RadioButton01 = new javax.swing.JRadioButton();
        RadioButton02 = new javax.swing.JRadioButton();
        Button01 = new javax.swing.JButton();
        Panel03 = new javax.swing.JPanel();
        Label02 = new javax.swing.JLabel();
        Label03 = new javax.swing.JLabel();
        Label04 = new javax.swing.JLabel();
        TextField02 = new javax.swing.JTextField();
        TextField03 = new javax.swing.JTextField();
        TextField04 = new javax.swing.JTextField();
        Label05 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextField05 = new javax.swing.JTextField();
        TextField06 = new javax.swing.JTextField();
        Button02 = new javax.swing.JButton();
        Panel05 = new javax.swing.JPanel();
        ScrollPane01 = new javax.swing.JScrollPane();
        TextArea01 = new javax.swing.JTextArea();
        Panel06 = new javax.swing.JPanel();
        Panel04 = new javax.swing.JPanel();
        CheckBox01 = new javax.swing.JCheckBox();
        CheckBox02 = new javax.swing.JCheckBox();
        Button03 = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        Menu01 = new javax.swing.JMenu();
        MenuItem01 = new javax.swing.JMenuItem();
        MenuItem02 = new javax.swing.JMenuItem();
        Separator01 = new javax.swing.JPopupMenu.Separator();
        MenuItem03 = new javax.swing.JMenuItem();

        FileChooser.setAcceptAllFileFilterUsed(false);
        FileChooser.setDialogTitle("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JFileChooser");
        setMinimumSize(new java.awt.Dimension(840, 620));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Panel01.setBorder(javax.swing.BorderFactory.createTitledBorder("Query"));
        Panel01.setLayout(new java.awt.GridBagLayout());

        Panel02.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Panel02.setLayout(new java.awt.GridBagLayout());

        Label01.setText("Search:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        Panel02.add(Label01, gridBagConstraints);

        TextField01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField01.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        Panel02.add(TextField01, gridBagConstraints);

        buttonGroup01.add(RadioButton01);
        RadioButton01.setSelected(true);
        RadioButton01.setText("ID");
        RadioButton01.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        Panel02.add(RadioButton01, gridBagConstraints);

        buttonGroup01.add(RadioButton02);
        RadioButton02.setText("Name");
        RadioButton02.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        Panel02.add(RadioButton02, gridBagConstraints);

        Button01.setText("Go");
        Button01.setEnabled(false);
        Button01.setNextFocusableComponent(TextArea01);
        Button01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button01ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        Panel02.add(Button01, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        Panel01.add(Panel02, gridBagConstraints);

        Panel03.setLayout(new java.awt.GridBagLayout());

        Label02.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel03.add(Label02, gridBagConstraints);

        Label03.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel03.add(Label03, gridBagConstraints);

        Label04.setText("Other Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel03.add(Label04, gridBagConstraints);

        TextField02.setEditable(false);
        TextField02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 5, 5);
        Panel03.add(TextField02, gridBagConstraints);

        TextField03.setEditable(false);
        TextField03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 5, 5);
        Panel03.add(TextField03, gridBagConstraints);

        TextField04.setEditable(false);
        TextField04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 5, 0);
        Panel03.add(TextField04, gridBagConstraints);

        Label05.setText("Career");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel03.add(Label05, gridBagConstraints);

        jLabel1.setText("Semester");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel03.add(jLabel1, gridBagConstraints);

        TextField05.setEditable(false);
        TextField05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 5, 5);
        Panel03.add(TextField05, gridBagConstraints);

        TextField06.setEditable(false);
        TextField06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 5, 5);
        Panel03.add(TextField06, gridBagConstraints);

        Button02.setText("Clear");
        Button02.setEnabled(false);
        Button02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button02ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        Panel03.add(Button02, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 5, 10);
        Panel01.add(Panel03, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 176;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        getContentPane().add(Panel01, gridBagConstraints);

        Panel05.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        Panel05.setLayout(new javax.swing.BoxLayout(Panel05, javax.swing.BoxLayout.LINE_AXIS));

        TextArea01.setEditable(false);
        TextArea01.setColumns(20);
        TextArea01.setRows(5);
        TextArea01.setMaximumSize(new java.awt.Dimension(164, 94));
        TextArea01.setMinimumSize(new java.awt.Dimension(164, 94));
        ScrollPane01.setViewportView(TextArea01);

        Panel05.add(ScrollPane01);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 745;
        gridBagConstraints.ipady = 396;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 11, 10);
        getContentPane().add(Panel05, gridBagConstraints);

        Panel06.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        Panel04.setLayout(new java.awt.GridBagLayout());

        CheckBox01.setText("Read");
        CheckBox01.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        Panel04.add(CheckBox01, gridBagConstraints);

        CheckBox02.setText("Write");
        CheckBox02.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        Panel04.add(CheckBox02, gridBagConstraints);

        Button03.setText("Modify");
        Button03.setEnabled(false);
        Button03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button03ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        Panel04.add(Button03, gridBagConstraints);

        javax.swing.GroupLayout Panel06Layout = new javax.swing.GroupLayout(Panel06);
        Panel06.setLayout(Panel06Layout);
        Panel06Layout.setHorizontalGroup(
            Panel06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(Panel06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel06Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Panel04, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Panel06Layout.setVerticalGroup(
            Panel06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Panel06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel06Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Panel04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        getContentPane().add(Panel06, gridBagConstraints);

        Menu01.setText("File");

        MenuItem01.setText("New List");
        Menu01.add(MenuItem01);

        MenuItem02.setText("Open List...");
        MenuItem02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem02ActionPerformed(evt);
            }
        });
        Menu01.add(MenuItem02);
        Menu01.add(Separator01);

        MenuItem03.setText("Exit");
        MenuItem03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem03ActionPerformed(evt);
            }
        });
        Menu01.add(MenuItem03);

        MenuBar.add(Menu01);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem02ActionPerformed
        path = new File(currDir);
        FileChooser.setCurrentDirectory(path);
        
        int optionSelected = FileChooser.showOpenDialog(this);
//        System.out.println("Option Selected: " + optionSelected);
        if (optionSelected == JFileChooser.APPROVE_OPTION) {
            BufferedReader br = null;
            FileReader fr = null;
            try {
                f = FileChooser.getSelectedFile();
                if (f.isFile() && f.canRead()) {
                    TextArea01.selectAll();
                    TextArea01.replaceSelection("");

                    count = 0;
                    String nLine;
                    P08_Estudiante st;
                    stds = new P08_Estudiante[30];

                    fr = new FileReader(f);
                    br = new BufferedReader(fr);

                    while ((nLine = br.readLine()) != null) {
                        TextArea01.append(nLine);
                        TextArea01.append("\n");

                        step = nLine.length();
                        String[] tokens = nLine.split(" ");
                        st = new P08_Estudiante();
                        st.setMatricula(tokens[0]);
                        st.setApaterno(tokens[1]);
                        st.setAmaterno(tokens[2]);
                        st.setNombre(tokens[3]);
                        st.setCarrera(tokens[4]);
                        st.setSemestre(tokens[5]);
                        st.setLong(step);
                        stds[count] = st;
                        count++;
                    }

                    br.close();
                    TextField01.setEnabled(true);
                    RadioButton01.setEnabled(true);
                    RadioButton02.setEnabled(true);
                    Button01.setEnabled(true);

                    CheckBox01.setEnabled(true);
                    CheckBox02.setEnabled(true);
                    Button03.setEnabled(true);
                    if (f.canRead()) {
                        CheckBox01.setSelected(true);
                    }
                    if (f.canWrite()) {
                        CheckBox02.setSelected(true);
                    }
                }
            } catch (IOException ex) {
                System.out.println(ex);
            } finally {
                try {
                    if (fr != null) {
                        fr.close();
                    }
                } catch (IOException ex) {
                    System.out.println(ex);
                }
            }
        }
    }//GEN-LAST:event_MenuItem02ActionPerformed

    private void MenuItem03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem03ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuItem03ActionPerformed

    private void Button01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button01ActionPerformed
        String query = TextField01.getText();
        boolean found = false;
        int x = 0;
        int y;
        if (!query.isEmpty()) {
            for (int i = 0; i < this.count; i++) {
                if (RadioButton01.isSelected()) {
                    if (stds[i].getMatricula().compareTo(query) == 0) {
                        found = true;
                        y = x + stds[i].getLong();
                        TextArea01.requestFocus();
                        TextArea01.select(x, y);
                        TextField02.setText(stds[i].getNombre());
                        TextField03.setText(stds[i].getApaterno());
                        TextField04.setText(stds[i].getAmaterno());
                        TextField05.setText(stds[i].getCarrera());
                        TextField06.setText(stds[i].getSemestre());
                        Button02.setEnabled(true);
                        break;
                    }
                    x += stds[i].getLong() + 1;
                }
            }
            if (!found) {
                String title = "Error";
                String message = "ID not found. Try again.";
                TextField01.setText("");
                TextField01.requestFocus();
                JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Button01ActionPerformed

    private void Button02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button02ActionPerformed
        TextField01.setText("");
        TextField02.setText("");
        TextField03.setText("");
        TextField04.setText("");
        TextField05.setText("");
        TextField06.setText("");
        Button02.setEnabled(false);
    }//GEN-LAST:event_Button02ActionPerformed

    private void Button03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button03ActionPerformed
        try {
            if (CheckBox01.isSelected() && !CheckBox02.isSelected()) {
                f.setWritable(false, true);
            } else if (!CheckBox01.isSelected() && CheckBox02.isSelected()) {
                f.setReadable(false, true);
            }
            String title = "Good";
            String message = "Attributes changed.";
            JOptionPane.showMessageDialog(this, message, title, JOptionPane.INFORMATION_MESSAGE);
            CheckBox01.setEnabled(false);
            CheckBox02.setEnabled(false);
            Button03.setEnabled(false);
        } catch (SecurityException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_Button03ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new P08_JFileChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button01;
    private javax.swing.JButton Button02;
    private javax.swing.JButton Button03;
    private javax.swing.JCheckBox CheckBox01;
    private javax.swing.JCheckBox CheckBox02;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JLabel Label01;
    private javax.swing.JLabel Label02;
    private javax.swing.JLabel Label03;
    private javax.swing.JLabel Label04;
    private javax.swing.JLabel Label05;
    private javax.swing.JMenu Menu01;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MenuItem01;
    private javax.swing.JMenuItem MenuItem02;
    private javax.swing.JMenuItem MenuItem03;
    private javax.swing.JPanel Panel01;
    private javax.swing.JPanel Panel02;
    private javax.swing.JPanel Panel03;
    private javax.swing.JPanel Panel04;
    private javax.swing.JPanel Panel05;
    private javax.swing.JPanel Panel06;
    private javax.swing.JRadioButton RadioButton01;
    private javax.swing.JRadioButton RadioButton02;
    private javax.swing.JScrollPane ScrollPane01;
    private javax.swing.JPopupMenu.Separator Separator01;
    private javax.swing.JTextArea TextArea01;
    private javax.swing.JTextField TextField01;
    private javax.swing.JTextField TextField02;
    private javax.swing.JTextField TextField03;
    private javax.swing.JTextField TextField04;
    private javax.swing.JTextField TextField05;
    private javax.swing.JTextField TextField06;
    private javax.swing.ButtonGroup buttonGroup01;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void looknfeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.println(ex);
        }
    }
}
