package UNIDAD_3_PA;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author GuillermoToledano
 */
public class P09_Buttons extends JFrame {

    private final DefaultListModel Items;
    private final String[] Breakfast = {
        "Super Deluxe Breakfast Platter",
        "Deluxe Breakfast Platter",
        "Bacon & Egg Burrito",
        "Breakfast Sandwich",
        "Hash Browns",
        "Loaded Breakfast Burrito",
        "Pancakes Platter",
        "The Breakfast Burguer"};
    private final String[] Drinks = {
        "Tea",
        "Soda",
        "Orange Juice",
        "Café Punta del Cielo",
        "Hand-Scooped Vanilla Ice Cream Shake",
        "Hand-Scooped Chocolate Ice Cream Shake",
        "Hand-Scooped Strawberry Ice Cream Shake",
        "Hand-Scooped Oreo Cookie Ice Cream Shake"                
    };
    private final String[] Salads = {
        "Side Salad",
        "Crispy Chicken Salad",
        "Original Grilled Chicken Salad"
    };
    private final String[] Desserts = {
        "Super Cono",
        "Carrot Cake",
        "Chocolate Cake",
        "Chocolate Chip Cookie"
    };

    /**
     * Creates new form P10_Buttons
     */
    public P09_Buttons() {
        setLooknFeel();
        initComponents();        
        RadioButton01.setSelected(true);
        Items = new DefaultListModel();
        for (String item : Breakfast) {
            Items.addElement(item);
        }
        List01.setModel(Items);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup01 = new javax.swing.ButtonGroup();
        Panel01 = new javax.swing.JPanel();
        RadioButton01 = new javax.swing.JRadioButton();
        RadioButton02 = new javax.swing.JRadioButton();
        RadioButton03 = new javax.swing.JRadioButton();
        RadioButton04 = new javax.swing.JRadioButton();
        Panel02 = new javax.swing.JPanel();
        ScrollPane01 = new javax.swing.JScrollPane();
        List01 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 230));
        setMinimumSize(new java.awt.Dimension(480, 230));
        setPreferredSize(new java.awt.Dimension(480, 230));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Panel01.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));
        Panel01.setMaximumSize(new java.awt.Dimension(100, 160));
        Panel01.setMinimumSize(new java.awt.Dimension(100, 160));
        Panel01.setName(""); // NOI18N
        Panel01.setPreferredSize(new java.awt.Dimension(100, 160));
        Panel01.setLayout(new java.awt.GridBagLayout());

        buttonGroup01.add(RadioButton01);
        RadioButton01.setText("Breakfast");
        RadioButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton01ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 15);
        Panel01.add(RadioButton01, gridBagConstraints);

        buttonGroup01.add(RadioButton02);
        RadioButton02.setText("Drinks");
        RadioButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton02ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 15);
        Panel01.add(RadioButton02, gridBagConstraints);

        buttonGroup01.add(RadioButton03);
        RadioButton03.setText("Salads");
        RadioButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton03ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 15);
        Panel01.add(RadioButton03, gridBagConstraints);

        buttonGroup01.add(RadioButton04);
        RadioButton04.setText("Desserts");
        RadioButton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton04ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 15);
        Panel01.add(RadioButton04, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 39, 0);
        getContentPane().add(Panel01, gridBagConstraints);

        Panel02.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        Panel02.setMaximumSize(new java.awt.Dimension(330, 160));
        Panel02.setMinimumSize(new java.awt.Dimension(330, 160));
        Panel02.setPreferredSize(new java.awt.Dimension(330, 160));
        Panel02.setLayout(new java.awt.GridBagLayout());

        ScrollPane01.setMaximumSize(new java.awt.Dimension(275, 130));
        ScrollPane01.setMinimumSize(new java.awt.Dimension(275, 130));

        List01.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        List01.setMaximumSize(new java.awt.Dimension(200, 200));
        List01.setMinimumSize(new java.awt.Dimension(200, 200));
        List01.setPreferredSize(new java.awt.Dimension(200, 200));
        List01.setVisibleRowCount(10);
        ScrollPane01.setViewportView(List01);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 0);
        Panel02.add(ScrollPane01, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 39, 10);
        getContentPane().add(Panel02, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton01ActionPerformed
        Items.clear();
        for (String item : Breakfast) {
            Items.addElement(item);
        }
        List01.setModel(Items);
    }//GEN-LAST:event_RadioButton01ActionPerformed

    private void RadioButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton02ActionPerformed
        Items.clear();
        for (String item : Drinks) {
            Items.addElement(item);
        }
        List01.setModel(Items);
    }//GEN-LAST:event_RadioButton02ActionPerformed

    private void RadioButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton03ActionPerformed
        Items.clear();
        for (String item : Salads) {
            Items.addElement(item);
        }
        List01.setModel(Items);
    }//GEN-LAST:event_RadioButton03ActionPerformed

    private void RadioButton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton04ActionPerformed
        Items.clear();
        for (String item : Desserts) {
            Items.addElement(item);
        }
        List01.setModel(Items);
    }//GEN-LAST:event_RadioButton04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P09_Buttons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> List01;
    private javax.swing.JPanel Panel01;
    private javax.swing.JPanel Panel02;
    private javax.swing.JRadioButton RadioButton01;
    private javax.swing.JRadioButton RadioButton02;
    private javax.swing.JRadioButton RadioButton03;
    private javax.swing.JRadioButton RadioButton04;
    private javax.swing.JScrollPane ScrollPane01;
    private javax.swing.ButtonGroup buttonGroup01;
    // End of variables declaration//GEN-END:variables

    private void setLooknFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.println(ex);
        }
    }
}
