/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UNIDAD_3_PA;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author GuillermoToledano
 */
public class P10_JList extends javax.swing.JFrame {

    /**
     * Creates new form P10_JList
     */
    DefaultListModel Available;
    DefaultListModel Selected;

    public P10_JList() {
        setLooknFeel();
        initComponents();
        Available = new DefaultListModel();
        Selected = new DefaultListModel();
        List01.setModel(Available);
        List02.setModel(Selected);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Panel01 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List01 = new javax.swing.JList<>();
        CheckBox01 = new javax.swing.JCheckBox();
        TextField01 = new javax.swing.JTextField();
        Button01 = new javax.swing.JButton();
        Panel02 = new javax.swing.JPanel();
        Button02 = new javax.swing.JButton();
        Button03 = new javax.swing.JButton();
        Button04 = new javax.swing.JButton();
        Panel03 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        List02 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JList");
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Panel01.setBorder(javax.swing.BorderFactory.createTitledBorder("Available"));
        Panel01.setMaximumSize(new java.awt.Dimension(150, 300));
        Panel01.setMinimumSize(new java.awt.Dimension(150, 300));
        Panel01.setPreferredSize(new java.awt.Dimension(150, 300));
        Panel01.setLayout(new java.awt.GridBagLayout());

        List01.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(List01);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 151;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 10);
        Panel01.add(jScrollPane1, gridBagConstraints);

        CheckBox01.setText("New");
        CheckBox01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox01ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        Panel01.add(CheckBox01, gridBagConstraints);

        TextField01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField01.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 0);
        Panel01.add(TextField01, gridBagConstraints);

        Button01.setText("Add");
        Button01.setEnabled(false);
        Button01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button01ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 74, 5, 0);
        Panel01.add(Button01, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        getContentPane().add(Panel01, gridBagConstraints);

        Panel02.setMaximumSize(new java.awt.Dimension(150, 300));
        Panel02.setMinimumSize(new java.awt.Dimension(150, 300));
        Panel02.setPreferredSize(new java.awt.Dimension(150, 300));
        Panel02.setLayout(new java.awt.GridBagLayout());

        Button02.setText(">>");
        Button02.setMaximumSize(new java.awt.Dimension(50, 25));
        Button02.setMinimumSize(new java.awt.Dimension(50, 25));
        Button02.setPreferredSize(new java.awt.Dimension(50, 25));
        Button02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button02ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        Panel02.add(Button02, gridBagConstraints);

        Button03.setText("Exit");
        Button03.setMaximumSize(new java.awt.Dimension(50, 25));
        Button03.setMinimumSize(new java.awt.Dimension(50, 25));
        Button03.setPreferredSize(new java.awt.Dimension(50, 25));
        Button03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button03ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 6);
        Panel02.add(Button03, gridBagConstraints);

        Button04.setText("<<");
        Button04.setMaximumSize(new java.awt.Dimension(50, 25));
        Button04.setMinimumSize(new java.awt.Dimension(50, 25));
        Button04.setPreferredSize(new java.awt.Dimension(50, 25));
        Button04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button04ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        Panel02.add(Button04, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        getContentPane().add(Panel02, gridBagConstraints);

        Panel03.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected"));
        Panel03.setMaximumSize(new java.awt.Dimension(150, 300));
        Panel03.setMinimumSize(new java.awt.Dimension(150, 300));
        Panel03.setPreferredSize(new java.awt.Dimension(150, 300));
        Panel03.setLayout(new java.awt.GridBagLayout());

        List02.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(List02);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 95;
        gridBagConstraints.ipady = 121;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        Panel03.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        getContentPane().add(Panel03, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBox01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox01ActionPerformed
        TextField01.setEnabled(true);
        TextField01.requestFocus();
        Button01.setEnabled(true);
    }//GEN-LAST:event_CheckBox01ActionPerformed

    private void Button01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button01ActionPerformed
        String item = TextField01.getText();
        String message;
        String title;
        if (!item.isEmpty()) {
            if (!contains(item)) {
                Available.addElement(item);
                TextField01.setText("");
                TextField01.setEnabled(false);
                CheckBox01.setSelected(false);
                Button01.setEnabled(false);
            } else {
                message = "Specified element is already in the list.";
                title = "Error!";
                TextField01.setText("");
                JOptionPane.showMessageDialog(this, message, title,
                        JOptionPane.WARNING_MESSAGE);
            }
        } else {
            message = "Not valid input. Try again.";
            title = "Empty input!";
            JOptionPane.showMessageDialog(this, message, title,
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Button01ActionPerformed

    private void Button02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button02ActionPerformed
        String message;
        String title;
        if (!Available.isEmpty()) {
            if (!List01.isSelectionEmpty()) {
                int index = List01.getSelectedIndex();
                String item = Available.get(index).toString();
                Available.remove(index);
                Selected.addElement(item);
            } else {
                message = "Please select an item.";
                title = "Error";
                JOptionPane.showMessageDialog(this, message, title,
                        JOptionPane.WARNING_MESSAGE);
            }
        } else {
            message = "No items available!";
            title = "Error";
            JOptionPane.showMessageDialog(this, message, title, 
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Button02ActionPerformed

    private void Button03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button03ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Button03ActionPerformed

    private void Button04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button04ActionPerformed
        
    }//GEN-LAST:event_Button04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P10_JList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button01;
    private javax.swing.JButton Button02;
    private javax.swing.JButton Button03;
    private javax.swing.JButton Button04;
    private javax.swing.JCheckBox CheckBox01;
    private javax.swing.JList<String> List01;
    private javax.swing.JList<String> List02;
    private javax.swing.JPanel Panel01;
    private javax.swing.JPanel Panel02;
    private javax.swing.JPanel Panel03;
    private javax.swing.JTextField TextField01;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void setLooknFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P10_JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private boolean contains(String input) {
        for (int i = 0; i < Available.getSize(); i++) {
            String item = Available.get(i).toString();
            if (item.equalsIgnoreCase(input)) {
                return true;
            }
        }
        return false;
    }

}
