/*
 * UNIVERSIDAD AUTÓNOMA DE TAMAULIPAS
 * FACULTAD DE INGENENIERÍA "ARTURO NARRO SILLER"
 * CURSO DE VERANO 2019 - 2 
 * PROGRAMACIÓN ORIENTADA A OBJETOS
 * PROFESOR: MCC. GARCÍA RUIZ ALEJANDRO H.
 * CONTACTO: ahgarcia@docentes.uat.edu.mx
 * 
 * EQUIPO
 * 
 * INTEGRANTES:
 * NOMBRE1
 * NOMBRE2
 * 
 * CONTACTO EQUIPO: 
 */

package Unidad5_Excepciones;

/**
 *
 * @author Alejandro_GarciaRuiz
 */
public class Introduccion {
    /*
    CUANDO DESARROLLAMOS UN PROGRAMA
    DEBEMOS ASEGURARNOS QUE EL USUARIO ENTIENDA LO MEJOR POSIBLE
    LAS INDICACIONES PARA EVITAR QUE INGRESE VALORES NO VALIDOS.
    SIN EMBARGO, EN MUCHAS OCASIONES, LOS USUARIOS POR FALTA 
    DE ATENCIÓN, ENTENDIMIENTO O POR MERÁ CURIOSIDAD INGRESAN 
    VALORES INVALIDOS AL PROGRAMA. 
    
    EN ESTE SENTIDO, ES OBLIGACIÓN DEL PROGRAMADOR INTEGRAR 
    MECANISMOS QUE PERMITAN AL SISTEMA LA TOLERANCIA A FALLOS. 
    LOGRANDO DE ESTA FORMA QUE EL SISTEMA CONTINUE EJECUTANDOSÉ 
    SATISFACTORIAMENTE E INDIQUE AL USUARIO LA FALLA OCURRIDA.
    
    PARA AYUDAR A LOS MECANISMOS A PROTECCIÓN DEL SISTEMA 
    ES POSIBLE EMPLEAR A LAS DENOMINADAS EXCEPCIONES. 
    
    UNA EXCEPCIÓN ES UN ERROR ORIGINADO DENTRO DEL PROGRAMA.
    
    NOTA. NO TODOS LAS EXCEPCIONES SON CAUSADAS POR CULPA DEL USUARIO
    
    
    EN JAVA, PARA TRABAJR CON EXCEPCIONES EXISTEN 5 PALABRAS RESERVADAS:
    
    try        - bloque de captura de expcepciones
    catch      - proceso a relizar cuando se captura una excepcion
    finally    - proceso realizado si se encuentre o no una excepción
    
    throw    - lanzador de excepciones
    throws   - 
    
    */
}
