/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_aerolinea;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class Interfaz extends javax.swing.JFrame {
    private int BOLETOS;
    private float PRICE;
    private String ESCAL, DEST, ASIENTO, HOR;
    private int VUELO;
    Interfaz[] vuelos = new Interfaz[20];
    int cont = 0;
    public Interfaz(int VUELO, int BOLETOS, float PRICE, String ESCAL, String DEST, String ASIENTO, String HOR) {
        this.VUELO = VUELO;
        this.BOLETOS = BOLETOS;
        this.PRICE = PRICE;
        this.ESCAL = ESCAL;
        this.DEST = DEST;
        this.ASIENTO = ASIENTO;
        this.HOR = HOR;
    }

    public int getBOLETOS() {
        return BOLETOS;
    }

    public float getPRICE() {
        return PRICE;
    }

    public String getESCAL() {
        return ESCAL;
    }

    public String getDEST() {
        return DEST;
    }

    public String getASIENTO() {
        return ASIENTO;
    }

    public String getHOR() {
        return HOR;
    }

    public int getVUELO() {
        return VUELO;
    }

    public void setVUELO(int VUELO) {
        this.VUELO = VUELO;
    }

    public Interfaz(int VUELO) {
        this.VUELO = VUELO;
    }

    @Override
    public String toString() {
        return "VUELO=" + VUELO + ", BOLETOS=" + BOLETOS + ", PRICE="
                + PRICE + ", ESCALA A=" + ESCAL + ", DESTINO A=" + DEST
                + ", ASIENTO=" + ASIENTO + ", HOR=" + HOR;
    }

    public Interfaz() {
        this.PRICE = 1099.99f;
        this.BOLETOS = 1;
        initComponents();
        jDialog1.setBounds(1, 0, 400, 340);
        NumBoletos.setText(Integer.toString(BOLETOS));
        this.getContentPane().setBackground(Color.WHITE);
        ToggleButton01.setSelected(true);
        ToggleButton03.setSelected(true);
        ToggleButton05.setSelected(true);
        ToggleButton07.setSelected(true);
        ToggleButton09.setSelected(true);
        ToggleButton12.setSelected(true);
        ToggleButton14.setSelected(true);
        ToggleButton16.setSelected(true);
        Label10.setText("$" + this.PRICE);
        this.ESCAL = ToggleButton01.getText();
        this.DEST = ToggleButton03.getText();
        this.ASIENTO = ToggleButton05.getText();
        this.HOR = ToggleButton07.getText();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Label04 = new javax.swing.JLabel();
        ToggleButton07 = new javax.swing.JToggleButton();
        ToggleButton08 = new javax.swing.JToggleButton();
        Label05 = new javax.swing.JLabel();
        ToggleButton09 = new javax.swing.JToggleButton();
        ToggleButton10 = new javax.swing.JToggleButton();
        ToggleButton11 = new javax.swing.JToggleButton();
        Label06 = new javax.swing.JLabel();
        Label01 = new javax.swing.JLabel();
        ToggleButton01 = new javax.swing.JToggleButton();
        ToggleButton02 = new javax.swing.JToggleButton();
        Label07 = new javax.swing.JLabel();
        Label02 = new javax.swing.JLabel();
        ToggleButton14 = new javax.swing.JToggleButton();
        ToggleButton03 = new javax.swing.JToggleButton();
        ToggleButton15 = new javax.swing.JToggleButton();
        ToggleButton04 = new javax.swing.JToggleButton();
        Label08 = new javax.swing.JLabel();
        Label03 = new javax.swing.JLabel();
        ToggleButton16 = new javax.swing.JToggleButton();
        ToggleButton12 = new javax.swing.JToggleButton();
        ToggleButton17 = new javax.swing.JToggleButton();
        Label09 = new javax.swing.JLabel();
        ToggleButton13 = new javax.swing.JToggleButton();
        NumBoletos = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();
        mas = new javax.swing.JButton();
        Button01 = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        ToggleButton05 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        ToggleButton06 = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Nuevo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(32, 32, 32))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label04.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label04.setForeground(new java.awt.Color(255, 0, 0));
        Label04.setText("Horario");

        ToggleButton07.setText("Matutino");
        ToggleButton07.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton07.setFocusPainted(false);
        ToggleButton07.setFocusable(false);
        ToggleButton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton07ActionPerformed(evt);
            }
        });

        ToggleButton08.setText("Vespertino");
        ToggleButton08.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton08.setFocusPainted(false);
        ToggleButton08.setFocusable(false);
        ToggleButton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton08ActionPerformed(evt);
            }
        });

        Label05.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label05.setForeground(new java.awt.Color(255, 0, 0));
        Label05.setText("Clase");

        ToggleButton09.setText("Standard");
        ToggleButton09.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton09.setFocusPainted(false);
        ToggleButton09.setFocusable(false);
        ToggleButton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton09ActionPerformed(evt);
            }
        });

        ToggleButton10.setText("Primera Clase Premium");
        ToggleButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton10.setFocusPainted(false);
        ToggleButton10.setFocusable(false);
        ToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton10ActionPerformed(evt);
            }
        });

        ToggleButton11.setText("Paquito Tear (Crack Pro Diosito)");
        ToggleButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton11.setFocusPainted(false);
        ToggleButton11.setFocusable(false);
        ToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton11ActionPerformed(evt);
            }
        });

        Label06.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label06.setForeground(new java.awt.Color(255, 0, 0));
        Label06.setText("Aerolinia");

        Label01.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label01.setForeground(new java.awt.Color(255, 0, 0));
        Label01.setText("Escala");

        ToggleButton01.setText("Simple");
        ToggleButton01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton01.setFocusPainted(false);
        ToggleButton01.setFocusable(false);
        ToggleButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton01ActionPerformed(evt);
            }
        });

        ToggleButton02.setText("Doble");
        ToggleButton02.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton02.setFocusPainted(false);
        ToggleButton02.setFocusable(false);
        ToggleButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton02ActionPerformed(evt);
            }
        });

        Label07.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label07.setForeground(new java.awt.Color(255, 0, 0));
        Label07.setText("Equipaje");

        Label02.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label02.setForeground(new java.awt.Color(255, 0, 0));
        Label02.setText("Destino");

        ToggleButton14.setText("Normal");
        ToggleButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton14.setFocusPainted(false);
        ToggleButton14.setFocusable(false);
        ToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton14ActionPerformed(evt);
            }
        });

        ToggleButton03.setText("Dubai");
        ToggleButton03.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton03.setFocusPainted(false);
        ToggleButton03.setFocusable(false);
        ToggleButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton03ActionPerformed(evt);
            }
        });

        ToggleButton15.setText("Extra");
        ToggleButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton15.setFocusPainted(false);
        ToggleButton15.setFocusable(false);
        ToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton15ActionPerformed(evt);
            }
        });

        ToggleButton04.setText("Abudhabi");
        ToggleButton04.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton04.setFocusPainted(false);
        ToggleButton04.setFocusable(false);
        ToggleButton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton04ActionPerformed(evt);
            }
        });

        Label08.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label08.setForeground(new java.awt.Color(255, 0, 0));
        Label08.setText("Aeropuerto");

        Label03.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label03.setForeground(new java.awt.Color(255, 0, 0));
        Label03.setText("Asiento");

        ToggleButton16.setText("Sur");
        ToggleButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton16.setFocusPainted(false);
        ToggleButton16.setFocusable(false);
        ToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton16ActionPerformed(evt);
            }
        });

        ToggleButton12.setText("AeroMexico");
        ToggleButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton12.setFocusPainted(false);
        ToggleButton12.setFocusable(false);
        ToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton12ActionPerformed(evt);
            }
        });

        ToggleButton17.setText("Este");
        ToggleButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton17.setFocusPainted(false);
        ToggleButton17.setFocusable(false);
        ToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton17ActionPerformed(evt);
            }
        });

        Label09.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label09.setForeground(new java.awt.Color(51, 153, 0));
        Label09.setText("Precio Total:");

        ToggleButton13.setText("InterJet");
        ToggleButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton13.setFocusPainted(false);
        ToggleButton13.setFocusable(false);
        ToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton13ActionPerformed(evt);
            }
        });

        NumBoletos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        NumBoletos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumBoletos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Label10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label10.setForeground(new java.awt.Color(204, 204, 0));
        Label10.setText("$0.0");

        mas.setText("+");
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });

        Button01.setText("Generar");
        Button01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button01ActionPerformed(evt);
            }
        });

        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        ToggleButton05.setText("Individual");
        ToggleButton05.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton05.setFocusPainted(false);
        ToggleButton05.setFocusable(false);
        ToggleButton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton05ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("°|=Escoje tu Mejor Opcion=|°");

        ToggleButton06.setText("Pareja");
        ToggleButton06.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton06.setFocusPainted(false);
        ToggleButton06.setFocusable(false);
        ToggleButton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton06ActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mas)
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(Label09, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Label10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button01)
                                .addGap(12, 12, 12)
                                .addComponent(jButton4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ToggleButton01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(Label01))
                                .addComponent(ToggleButton07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ToggleButton08, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(ToggleButton02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(Label04)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ToggleButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ToggleButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(Label06)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ToggleButton04, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Label02)
                                        .addGap(37, 37, 37))
                                    .addComponent(ToggleButton03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ToggleButton06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Label05)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(ToggleButton05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Label03)
                                        .addGap(57, 57, 57))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ToggleButton09, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ToggleButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ToggleButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ToggleButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(Label08)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ToggleButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ToggleButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(Label07)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ToggleButton01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ToggleButton02))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label02)
                                    .addComponent(Label01)
                                    .addComponent(Label03))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ToggleButton03)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ToggleButton04))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ToggleButton05)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ToggleButton06)))
                        .addGap(67, 67, 67)
                        .addComponent(ToggleButton08))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label05)
                            .addComponent(Label04))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToggleButton09)
                            .addComponent(ToggleButton10)
                            .addComponent(ToggleButton07))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToggleButton11)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label06)
                            .addComponent(Label08))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToggleButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToggleButton13))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(ToggleButton16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ToggleButton17))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Label07)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ToggleButton14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ToggleButton15))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NumBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(menos)
                            .addGap(19, 19, 19))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(mas)
                            .addGap(22, 22, 22)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Label09)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button01)
                            .addComponent(jButton4))
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToggleButton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton07ActionPerformed
        ToggleButton07.setSelected(true);
        HOR = ToggleButton07.getText();
        if (ToggleButton08.isSelected()) {
            ToggleButton08.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE -= 200.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton07ActionPerformed

    private void ToggleButton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton08ActionPerformed
        ToggleButton08.setSelected(true);
        HOR = ToggleButton08.getText();
        if (ToggleButton07.isSelected()) {
            ToggleButton07.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE += 200.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton08ActionPerformed

    private void ToggleButton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton09ActionPerformed
        ToggleButton09.setSelected(true);
        if (ToggleButton10.isSelected()) {
            this.PRICE /= this.BOLETOS;
            this.PRICE -= 60.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        } else if (ToggleButton11.isSelected()) {
            this.PRICE /= this.BOLETOS;
            this.PRICE -= 70.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
        ToggleButton10.setSelected(false);
        ToggleButton11.setSelected(false);
    }//GEN-LAST:event_ToggleButton09ActionPerformed

    private void ToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton10ActionPerformed
        ToggleButton10.setSelected(true);
        if (ToggleButton09.isSelected()) {
            this.PRICE /= this.BOLETOS;
            this.PRICE += 60.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        } else if (ToggleButton11.isSelected()) {
            this.PRICE /= this.BOLETOS;
            this.PRICE -= 10.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
        ToggleButton09.setSelected(false);
        ToggleButton11.setSelected(false);
    }//GEN-LAST:event_ToggleButton10ActionPerformed

    private void ToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton11ActionPerformed
        ToggleButton11.setSelected(true);
        if (ToggleButton09.isSelected()) {
            this.PRICE /= this.BOLETOS;
            this.PRICE += 70.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        } else if (ToggleButton10.isSelected()) {
            this.PRICE /= this.BOLETOS;
            this.PRICE += 10.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
        ToggleButton09.setSelected(false);
        ToggleButton10.setSelected(false);
    }//GEN-LAST:event_ToggleButton11ActionPerformed

    private void ToggleButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton01ActionPerformed
        ToggleButton01.setSelected(true);
        this.ESCAL = ToggleButton01.getText();
        if (ToggleButton02.isSelected()) {
            ToggleButton02.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE -= 60.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton01ActionPerformed

    private void ToggleButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton02ActionPerformed
        ToggleButton02.setSelected(true);
        this.ESCAL = ToggleButton02.getText();
        if (ToggleButton01.isSelected()) {
            ToggleButton01.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE += 60.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton02ActionPerformed

    private void ToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton14ActionPerformed
        ToggleButton14.setSelected(true);
        if (ToggleButton15.isSelected()) {
            ToggleButton15.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE -= 200.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton14ActionPerformed

    private void ToggleButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton03ActionPerformed
        ToggleButton03.setSelected(true);
        this.DEST = ToggleButton03.getText();
        if (ToggleButton04.isSelected()) {
            ToggleButton04.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE -= 60.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton03ActionPerformed

    private void ToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton15ActionPerformed
        ToggleButton15.setSelected(true);
        if (ToggleButton14.isSelected()) {
            ToggleButton14.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE += 200.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton15ActionPerformed

    private void ToggleButton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton04ActionPerformed
        ToggleButton04.setSelected(true);
        this.DEST = ToggleButton04.getText();
        if (ToggleButton03.isSelected()) {
            ToggleButton03.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE += 60.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton04ActionPerformed

    private void ToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton16ActionPerformed
        ToggleButton16.setSelected(true);
        if (ToggleButton17.isSelected()) {
            ToggleButton17.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE -= 150.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton16ActionPerformed

    private void ToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton12ActionPerformed
        ToggleButton12.setSelected(true);
        if (ToggleButton13.isSelected()) {
            ToggleButton13.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE -= 150.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton12ActionPerformed

    private void ToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton17ActionPerformed
        ToggleButton17.setSelected(true);
        if (ToggleButton16.isSelected()) {
            ToggleButton16.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE += 150.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton17ActionPerformed

    private void ToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton13ActionPerformed
        ToggleButton13.setSelected(true);
        if (ToggleButton12.isSelected()) {
            ToggleButton12.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE += 150.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton13ActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        float Precio = this.PRICE / this.BOLETOS;
        this.BOLETOS++;
        this.PRICE += Precio;
        NumBoletos.setText(Integer.toString(BOLETOS));
        Label10.setText("$" + this.PRICE);
    }//GEN-LAST:event_masActionPerformed

    private void Button01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button01ActionPerformed
        jDialog1.setVisible(true);
        jTextArea1.setText(null);
        for (int i = 0; i < cont; i++) {
            jTextArea1.append(vuelos[i].toString());
            jTextArea1.append(System.getProperty("line.separator"));
        }
    }//GEN-LAST:event_Button01ActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        if (this.BOLETOS > 1) {
            float Precio = this.PRICE / this.BOLETOS;
            this.PRICE -= Precio;
            this.BOLETOS--;
            NumBoletos.setText(Integer.toString(BOLETOS));
            Label10.setText("$" + this.PRICE);
        }

    }//GEN-LAST:event_menosActionPerformed

    private void ToggleButton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton05ActionPerformed
        ToggleButton05.setSelected(true);
        this.ASIENTO = ToggleButton05.getText();
        if (ToggleButton06.isSelected()) {
            ToggleButton06.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE -= 60.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton05ActionPerformed

    private void ToggleButton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton06ActionPerformed
        ToggleButton06.setSelected(true);
        this.ASIENTO = ToggleButton06.getText();
        if (ToggleButton05.isSelected()) {
            ToggleButton05.setSelected(false);
            this.PRICE /= this.BOLETOS;
            this.PRICE += 60.0f;
            this.PRICE *= this.BOLETOS;
            Label10.setText("$" + this.PRICE);
        }
    }//GEN-LAST:event_ToggleButton06ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String result = JOptionPane.showInputDialog("Ingrese el numero del vuelo a checar:...");
        JOptionPane.showMessageDialog(null, vuelos[Integer.parseInt(result) - 1].toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (cont < vuelos.length) {
            vuelos[cont] = new Interfaz((cont + 1), BOLETOS, PRICE, ESCAL, DEST, ASIENTO, HOR);
            cont++;
        } else {
            String message = "La Memoria esta llena, se recomienda eliminar Vuelos";
            JOptionPane.showMessageDialog(null, message);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String result = JOptionPane.showInputDialog("Ingrese el numero de vuelo a eliminar:...");
        if (cont != vuelos.length) {
            for (int i = Integer.parseInt(result) - 1; i < cont - 1; i++) {
                vuelos[i] = vuelos[i + 1];
                vuelos[i].setVUELO(i + 1);
            }
            vuelos[cont] = null;
            cont--;
        } else {
            for (int i = Integer.parseInt(result) - 1; i < cont-1; i++) {
                vuelos[i] = vuelos[i + 1];
                vuelos[i].setVUELO(i + 1);
                
            }
            vuelos[cont-1] = null;
            cont--;
        }

        jTextArea1.setText(null);
        for (int i = 0; i < cont; i++) {
            jTextArea1.append(vuelos[i].toString());
            jTextArea1.append(System.getProperty("line.separator"));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jDialog1.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button01;
    private javax.swing.JLabel Label01;
    private javax.swing.JLabel Label02;
    private javax.swing.JLabel Label03;
    private javax.swing.JLabel Label04;
    private javax.swing.JLabel Label05;
    private javax.swing.JLabel Label06;
    private javax.swing.JLabel Label07;
    private javax.swing.JLabel Label08;
    private javax.swing.JLabel Label09;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel NumBoletos;
    private javax.swing.JToggleButton ToggleButton01;
    private javax.swing.JToggleButton ToggleButton02;
    private javax.swing.JToggleButton ToggleButton03;
    private javax.swing.JToggleButton ToggleButton04;
    private javax.swing.JToggleButton ToggleButton05;
    private javax.swing.JToggleButton ToggleButton06;
    private javax.swing.JToggleButton ToggleButton07;
    private javax.swing.JToggleButton ToggleButton08;
    private javax.swing.JToggleButton ToggleButton09;
    private javax.swing.JToggleButton ToggleButton10;
    private javax.swing.JToggleButton ToggleButton11;
    private javax.swing.JToggleButton ToggleButton12;
    private javax.swing.JToggleButton ToggleButton13;
    private javax.swing.JToggleButton ToggleButton14;
    private javax.swing.JToggleButton ToggleButton15;
    private javax.swing.JToggleButton ToggleButton16;
    private javax.swing.JToggleButton ToggleButton17;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    // End of variables declaration//GEN-END:variables
}
