/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UNIDAD_1_PA;

import Recursos.P11_User;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author GuillermoToledano
 */
public class P11_JTextField extends javax.swing.JFrame {
    
    P11_User USER;
    /**
     * Creates new form P5_JTextField
     */
    public P11_JTextField() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label01 = new javax.swing.JLabel();
        Label02 = new javax.swing.JLabel();
        Label03 = new javax.swing.JLabel();
        Label04 = new javax.swing.JLabel();
        Label05 = new javax.swing.JLabel();
        Label06 = new javax.swing.JLabel();
        TextField01 = new javax.swing.JTextField();
        TextField02 = new javax.swing.JTextField();
        TextField03 = new javax.swing.JTextField();
        TextField04 = new javax.swing.JTextField();
        Label07 = new javax.swing.JLabel();
        ToggleButton01 = new javax.swing.JToggleButton();
        Button01 = new javax.swing.JButton();
        Button02 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTextField");
        setMinimumSize(new java.awt.Dimension(400, 270));
        setResizable(false);

        Label01.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Label01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label01.setText("Form");
        Label01.setFocusable(false);
        Label01.setRequestFocusEnabled(false);
        Label01.setVerifyInputWhenFocusTarget(false);

        Label02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ModernXP-15-Group-icon.png"))); // NOI18N

        Label03.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Label03.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label03.setText("Name");
        Label03.setFocusable(false);
        Label03.setRequestFocusEnabled(false);
        Label03.setVerifyInputWhenFocusTarget(false);

        Label04.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Label04.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label04.setText("Last Name");
        Label04.setFocusable(false);
        Label04.setRequestFocusEnabled(false);
        Label04.setVerifyInputWhenFocusTarget(false);

        Label05.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Label05.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label05.setText("Phone Number");

        Label06.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Label06.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label06.setText("E-mail");

        TextField01.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TextField01.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextField01.setToolTipText("");
        TextField01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TextField02.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TextField02.setToolTipText("");

        TextField03.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TextField04.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        Label07.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Label07.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label07.setText("Donator");
        Label07.setFocusable(false);
        Label07.setRequestFocusEnabled(false);
        Label07.setVerifyInputWhenFocusTarget(false);

        ToggleButton01.setSelected(true);
        ToggleButton01.setText("YES");
        ToggleButton01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToggleButton01.setFocusPainted(false);
        ToggleButton01.setFocusable(false);
        ToggleButton01.setRequestFocusEnabled(false);
        ToggleButton01.setRolloverEnabled(false);
        ToggleButton01.setVerifyInputWhenFocusTarget(false);
        ToggleButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton01ActionPerformed(evt);
            }
        });

        Button01.setText("Confirm");
        Button01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button01ActionPerformed(evt);
            }
        });

        Button02.setText("Reset");
        Button02.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label01, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label02)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label03, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Label04, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Label05)
                                            .addComponent(Label06, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextField01, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField02, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField03, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextField04, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Label07)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ToggleButton01))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Button02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button01)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Label03, Label04, Label05, Label06, Label07});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TextField01, TextField02, TextField03, TextField04});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Button01, Button02});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Label01, Label02});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Label01)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(TextField01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label03, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Label04, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Label05, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Label06, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Label07)
                            .addComponent(ToggleButton01)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Label02)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button02)
                    .addComponent(Button01))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Button01, Button02, Label03, Label04, Label05, Label06, Label07, ToggleButton01});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TextField01, TextField02, TextField03, TextField04});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToggleButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton01ActionPerformed
        boolean selected = ToggleButton01.isSelected();
        if (selected) {
            ToggleButton01.setText("YES");
        } else {
            ToggleButton01.setText("NO");
        }
    }//GEN-LAST:event_ToggleButton01ActionPerformed

    private void Button02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button02ActionPerformed
        clearComp();
    }//GEN-LAST:event_Button02ActionPerformed

    private void Button01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button01ActionPerformed
        if (!allFilled()) {
            JOptionPane.showMessageDialog(this, "Please, fill all the blanks.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        } else {            
            String name = TextField01.getText();
            String last_name = TextField02.getText();
            String phone = TextField03.getText();
            String email = TextField04.getText();
            boolean selected = ToggleButton01.isSelected();
            USER = new P11_User(name, last_name, phone, email, selected);
            String message = USER.toString();
            JOptionPane.showMessageDialog(this, message, "User Data", JOptionPane.INFORMATION_MESSAGE);
            clearComp();
        }
    }//GEN-LAST:event_Button01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P11_JTextField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P11_JTextField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P11_JTextField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P11_JTextField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P11_JTextField().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button01;
    private javax.swing.JButton Button02;
    private javax.swing.JLabel Label01;
    private javax.swing.JLabel Label02;
    private javax.swing.JLabel Label03;
    private javax.swing.JLabel Label04;
    private javax.swing.JLabel Label05;
    private javax.swing.JLabel Label06;
    private javax.swing.JLabel Label07;
    private javax.swing.JTextField TextField01;
    private javax.swing.JTextField TextField02;
    private javax.swing.JTextField TextField03;
    private javax.swing.JTextField TextField04;
    private javax.swing.JToggleButton ToggleButton01;
    // End of variables declaration//GEN-END:variables

    private boolean allFilled() {
        boolean flag = true;
        if (TextField01.getText().isEmpty()
                || TextField02.getText().isEmpty()
                || TextField03.getText().isEmpty()
                || TextField04.getText().isEmpty()) {
            flag = false;
        }
        return flag;
    }

    private void clearComp() {
        TextField01.setText("");
        TextField02.setText("");
        TextField03.setText("");
        TextField04.setText("");
        boolean selected = ToggleButton01.isSelected();
        if (!selected) {
            ToggleButton01.setText("YES");
            ToggleButton01.setSelected(true);
        }
    }
}
