/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UNIDAD_1_PA;

import javax.swing.JOptionPane;
import javax.swing.JFrame;
/**
 *
 * @author GuillermoToledano
 */
public class P14_JMenu extends JFrame {

    /**
     * Creates new form P7_JMenu
     */
    public P14_JMenu() {
        setLooknFeel();
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_CtoI = new javax.swing.JDialog();
        Label01 = new javax.swing.JLabel();
        TextField01 = new javax.swing.JTextField();
        Label2 = new javax.swing.JLabel();
        TextField02 = new javax.swing.JTextField();
        ButtonConvert_CtoI = new javax.swing.JButton();
        Button_Close_CtoI = new javax.swing.JButton();
        Dialog_CtoII = new javax.swing.JDialog();
        Label3 = new javax.swing.JLabel();
        TextField2 = new javax.swing.JTextField();
        Label4 = new javax.swing.JLabel();
        TextField3 = new javax.swing.JTextField();
        ButtonConvert_CtoI1 = new javax.swing.JButton();
        Button_Close_CtoI1 = new javax.swing.JButton();
        Dialog_CtoIII = new javax.swing.JDialog();
        Label5 = new javax.swing.JLabel();
        TextField4 = new javax.swing.JTextField();
        Label6 = new javax.swing.JLabel();
        TextField5 = new javax.swing.JTextField();
        ButtonConvert_CtoI2 = new javax.swing.JButton();
        Button_Close_CtoI2 = new javax.swing.JButton();
        Dialog_CtoIV = new javax.swing.JDialog();
        Label7 = new javax.swing.JLabel();
        TextField6 = new javax.swing.JTextField();
        Label8 = new javax.swing.JLabel();
        TextField7 = new javax.swing.JTextField();
        ButtonConvert_CtoI3 = new javax.swing.JButton();
        Button_Close_CtoI3 = new javax.swing.JButton();
        Dialog_CtoV = new javax.swing.JDialog();
        Label9 = new javax.swing.JLabel();
        TextField8 = new javax.swing.JTextField();
        Label10 = new javax.swing.JLabel();
        TextField9 = new javax.swing.JTextField();
        ButtonConvert_CtoI4 = new javax.swing.JButton();
        Button_Close_CtoI4 = new javax.swing.JButton();
        Dialog_CtoVI = new javax.swing.JDialog();
        Label11 = new javax.swing.JLabel();
        TextField10 = new javax.swing.JTextField();
        Label12 = new javax.swing.JLabel();
        TextField11 = new javax.swing.JTextField();
        ButtonConvert_CtoI5 = new javax.swing.JButton();
        Button_Close_CtoI5 = new javax.swing.JButton();
        Dialog_CtoVII = new javax.swing.JDialog();
        Label13 = new javax.swing.JLabel();
        TextField12 = new javax.swing.JTextField();
        Label14 = new javax.swing.JLabel();
        TextField13 = new javax.swing.JTextField();
        ButtonConvert_CtoI6 = new javax.swing.JButton();
        Button_Close_CtoI6 = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Salute = new javax.swing.JMenuItem();
        Separator1 = new javax.swing.JPopupMenu.Separator();
        Exit = new javax.swing.JMenuItem();
        Converter = new javax.swing.JMenu();
        Lenght = new javax.swing.JMenu();
        CtoI = new javax.swing.JMenuItem();
        MtoF = new javax.swing.JMenuItem();
        KtoM = new javax.swing.JMenuItem();
        Mass = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Temperature = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        Dialog_CtoI.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialog_CtoI.setTitle("Converter");
        Dialog_CtoI.setMinimumSize(new java.awt.Dimension(320, 115));
        Dialog_CtoI.setModal(true);
        Dialog_CtoI.setResizable(false);

        Label01.setText("Centimeter");

        TextField01.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField01.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Label2.setText("Inch");

        TextField02.setEditable(false);
        TextField02.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField02.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ButtonConvert_CtoI.setText("Convert");
        ButtonConvert_CtoI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonConvert_CtoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvert_CtoIActionPerformed(evt);
            }
        });

        Button_Close_CtoI.setText("Close");
        Button_Close_CtoI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_Close_CtoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Close_CtoIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_CtoILayout = new javax.swing.GroupLayout(Dialog_CtoI.getContentPane());
        Dialog_CtoI.getContentPane().setLayout(Dialog_CtoILayout);
        Dialog_CtoILayout.setHorizontalGroup(
            Dialog_CtoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField01, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonConvert_CtoI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dialog_CtoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Close_CtoI, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Dialog_CtoILayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Button_Close_CtoI, TextField02});

        Dialog_CtoILayout.setVerticalGroup(
            Dialog_CtoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_CtoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label01)
                    .addComponent(TextField01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label2)
                    .addComponent(TextField02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConvert_CtoI))
                .addGap(18, 18, 18)
                .addComponent(Button_Close_CtoI)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Dialog_CtoILayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonConvert_CtoI, Button_Close_CtoI, Label01, Label2, TextField01, TextField02});

        Dialog_CtoII.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialog_CtoII.setTitle("Converter");
        Dialog_CtoII.setMinimumSize(new java.awt.Dimension(320, 115));
        Dialog_CtoII.setModal(true);
        Dialog_CtoII.setResizable(false);

        Label3.setText("Meter");

        TextField2.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Label4.setText("Feet");

        TextField3.setEditable(false);
        TextField3.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ButtonConvert_CtoI1.setText("Convert");
        ButtonConvert_CtoI1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonConvert_CtoI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvert_CtoI1ActionPerformed(evt);
            }
        });

        Button_Close_CtoI1.setText("Close");
        Button_Close_CtoI1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_Close_CtoI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Close_CtoI1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_CtoIILayout = new javax.swing.GroupLayout(Dialog_CtoII.getContentPane());
        Dialog_CtoII.getContentPane().setLayout(Dialog_CtoIILayout);
        Dialog_CtoIILayout.setHorizontalGroup(
            Dialog_CtoIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoIILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonConvert_CtoI1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dialog_CtoIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Close_CtoI1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        Dialog_CtoIILayout.setVerticalGroup(
            Dialog_CtoIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoIILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_CtoIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label3)
                    .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label4)
                    .addComponent(TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConvert_CtoI1))
                .addGap(18, 18, 18)
                .addComponent(Button_Close_CtoI1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Dialog_CtoIII.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialog_CtoIII.setTitle("Converter");
        Dialog_CtoIII.setMinimumSize(new java.awt.Dimension(320, 115));
        Dialog_CtoIII.setModal(true);
        Dialog_CtoIII.setResizable(false);

        Label5.setText("Kilometers");

        TextField4.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Label6.setText("Miles");

        TextField5.setEditable(false);
        TextField5.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ButtonConvert_CtoI2.setText("Convert");
        ButtonConvert_CtoI2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonConvert_CtoI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvert_CtoI2ActionPerformed(evt);
            }
        });

        Button_Close_CtoI2.setText("Close");
        Button_Close_CtoI2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_Close_CtoI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Close_CtoI2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_CtoIIILayout = new javax.swing.GroupLayout(Dialog_CtoIII.getContentPane());
        Dialog_CtoIII.getContentPane().setLayout(Dialog_CtoIIILayout);
        Dialog_CtoIIILayout.setHorizontalGroup(
            Dialog_CtoIIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoIIILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonConvert_CtoI2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dialog_CtoIIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Close_CtoI2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        Dialog_CtoIIILayout.setVerticalGroup(
            Dialog_CtoIIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoIIILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_CtoIIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label5)
                    .addComponent(TextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label6)
                    .addComponent(TextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConvert_CtoI2))
                .addGap(18, 18, 18)
                .addComponent(Button_Close_CtoI2)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Dialog_CtoIV.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialog_CtoIV.setTitle("Converter");
        Dialog_CtoIV.setMinimumSize(new java.awt.Dimension(320, 115));
        Dialog_CtoIV.setModal(true);
        Dialog_CtoIV.setResizable(false);

        Label7.setText("Gram");

        TextField6.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Label8.setText("Ounce");

        TextField7.setEditable(false);
        TextField7.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ButtonConvert_CtoI3.setText("Convert");
        ButtonConvert_CtoI3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonConvert_CtoI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvert_CtoI3ActionPerformed(evt);
            }
        });

        Button_Close_CtoI3.setText("Close");
        Button_Close_CtoI3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_Close_CtoI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Close_CtoI3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_CtoIVLayout = new javax.swing.GroupLayout(Dialog_CtoIV.getContentPane());
        Dialog_CtoIV.getContentPane().setLayout(Dialog_CtoIVLayout);
        Dialog_CtoIVLayout.setHorizontalGroup(
            Dialog_CtoIVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoIVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonConvert_CtoI3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dialog_CtoIVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Close_CtoI3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        Dialog_CtoIVLayout.setVerticalGroup(
            Dialog_CtoIVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoIVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_CtoIVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label7)
                    .addComponent(TextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label8)
                    .addComponent(TextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConvert_CtoI3))
                .addGap(18, 18, 18)
                .addComponent(Button_Close_CtoI3)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Dialog_CtoV.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialog_CtoV.setTitle("Converter");
        Dialog_CtoV.setMinimumSize(new java.awt.Dimension(320, 115));
        Dialog_CtoV.setModal(true);
        Dialog_CtoV.setResizable(false);

        Label9.setText("Kilogram");

        TextField8.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Label10.setText("Pound");

        TextField9.setEditable(false);
        TextField9.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ButtonConvert_CtoI4.setText("Convert");
        ButtonConvert_CtoI4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonConvert_CtoI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvert_CtoI4ActionPerformed(evt);
            }
        });

        Button_Close_CtoI4.setText("Close");
        Button_Close_CtoI4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_Close_CtoI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Close_CtoI4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_CtoVLayout = new javax.swing.GroupLayout(Dialog_CtoV.getContentPane());
        Dialog_CtoV.getContentPane().setLayout(Dialog_CtoVLayout);
        Dialog_CtoVLayout.setHorizontalGroup(
            Dialog_CtoVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonConvert_CtoI4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dialog_CtoVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Close_CtoI4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dialog_CtoVLayout.setVerticalGroup(
            Dialog_CtoVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_CtoVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label9)
                    .addComponent(TextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label10)
                    .addComponent(TextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConvert_CtoI4))
                .addGap(18, 18, 18)
                .addComponent(Button_Close_CtoI4)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Dialog_CtoVI.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialog_CtoVI.setTitle("Converter");
        Dialog_CtoVI.setMinimumSize(new java.awt.Dimension(320, 115));
        Dialog_CtoVI.setModal(true);
        Dialog_CtoVI.setResizable(false);

        Label11.setText("Celsius");

        TextField10.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Label12.setText("Fahrenheit");

        TextField11.setEditable(false);
        TextField11.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ButtonConvert_CtoI5.setText("Convert");
        ButtonConvert_CtoI5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonConvert_CtoI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvert_CtoI5ActionPerformed(evt);
            }
        });

        Button_Close_CtoI5.setText("Close");
        Button_Close_CtoI5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_Close_CtoI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Close_CtoI5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_CtoVILayout = new javax.swing.GroupLayout(Dialog_CtoVI.getContentPane());
        Dialog_CtoVI.getContentPane().setLayout(Dialog_CtoVILayout);
        Dialog_CtoVILayout.setHorizontalGroup(
            Dialog_CtoVILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoVILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonConvert_CtoI5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dialog_CtoVILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Close_CtoI5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        Dialog_CtoVILayout.setVerticalGroup(
            Dialog_CtoVILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoVILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_CtoVILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label11)
                    .addComponent(TextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label12)
                    .addComponent(TextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConvert_CtoI5))
                .addGap(18, 18, 18)
                .addComponent(Button_Close_CtoI5)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Dialog_CtoVII.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialog_CtoVII.setTitle("Converter");
        Dialog_CtoVII.setMinimumSize(new java.awt.Dimension(320, 115));
        Dialog_CtoVII.setModal(true);
        Dialog_CtoVII.setResizable(false);

        Label13.setText("Celsius");

        TextField12.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Label14.setText("Farenheit");

        TextField13.setEditable(false);
        TextField13.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        TextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ButtonConvert_CtoI6.setText("Convert");
        ButtonConvert_CtoI6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonConvert_CtoI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConvert_CtoI6ActionPerformed(evt);
            }
        });

        Button_Close_CtoI6.setText("Close");
        Button_Close_CtoI6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_Close_CtoI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Close_CtoI6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_CtoVIILayout = new javax.swing.GroupLayout(Dialog_CtoVII.getContentPane());
        Dialog_CtoVII.getContentPane().setLayout(Dialog_CtoVIILayout);
        Dialog_CtoVIILayout.setHorizontalGroup(
            Dialog_CtoVIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoVIILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonConvert_CtoI6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dialog_CtoVIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Close_CtoI6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        Dialog_CtoVIILayout.setVerticalGroup(
            Dialog_CtoVIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_CtoVIILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_CtoVIILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label13)
                    .addComponent(TextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label14)
                    .addComponent(TextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConvert_CtoI6))
                .addGap(18, 18, 18)
                .addComponent(Button_Close_CtoI6)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JMenu");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        MenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        File.setText("File");

        Salute.setText("Say Hello");
        Salute.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Salute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaluteActionPerformed(evt);
            }
        });
        File.add(Salute);
        File.add(Separator1);

        Exit.setText("Exit");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        MenuBar.add(File);

        Converter.setText("Converter");

        Lenght.setText("Length");
        Lenght.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CtoI.setText("Centimeter to Inch");
        CtoI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CtoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtoIActionPerformed(evt);
            }
        });
        Lenght.add(CtoI);

        MtoF.setText("Meter to Feet");
        MtoF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MtoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtoFActionPerformed(evt);
            }
        });
        Lenght.add(MtoF);

        KtoM.setText("Kilometers to Miles");
        KtoM.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        KtoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KtoMActionPerformed(evt);
            }
        });
        Lenght.add(KtoM);

        Converter.add(Lenght);

        Mass.setText("Mass");
        Mass.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuItem1.setText("Gram to Ounce");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Mass.add(jMenuItem1);

        jMenuItem2.setText("Kilogram to Pound");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Mass.add(jMenuItem2);

        Converter.add(Mass);

        Temperature.setText("Temperature");
        Temperature.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuItem3.setText("Celsius to Fahrenheit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Temperature.add(jMenuItem3);

        jMenuItem4.setText("Celsius to Kelvin");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Temperature.add(jMenuItem4);

        Converter.add(Temperature);

        MenuBar.add(Converter);

        Help.setText("Help");

        About.setText("About");
        Help.add(About);

        MenuBar.add(Help);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaluteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaluteActionPerformed
        String title = "Salute";
        String mssge = "Hello friend! ";
        JOptionPane.showMessageDialog(this, mssge, title, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SaluteActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        String question = "Are you sure?";
        String bye = "See you later!";
        String title = "Exit option";
        int selected = JOptionPane.showConfirmDialog(this, question, title, JOptionPane.YES_NO_OPTION);
        switch (selected) {
            case JOptionPane.YES_OPTION:
                JOptionPane.showMessageDialog(this, bye, title, JOptionPane.INFORMATION_MESSAGE);
                System.exit(0);
                break;
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void CtoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtoIActionPerformed
        Dialog_CtoI.setVisible(true);
    }//GEN-LAST:event_CtoIActionPerformed

    private void ButtonConvert_CtoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConvert_CtoIActionPerformed
        double cm;
        double in;
        String input = TextField01.getText().trim();
        if (!input.isEmpty()) {
            cm = Double.parseDouble(input);
            in = cm * 0.39370;
            String output = String.valueOf(in);
            TextField02.setText(output);
        }
    }//GEN-LAST:event_ButtonConvert_CtoIActionPerformed

    private void Button_Close_CtoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Close_CtoIActionPerformed
        TextField01.setText("");
        TextField02.setText("");
        Dialog_CtoI.dispose();
    }//GEN-LAST:event_Button_Close_CtoIActionPerformed

    private void MtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtoFActionPerformed
    Dialog_CtoII.setVisible(true);
    }//GEN-LAST:event_MtoFActionPerformed

    private void ButtonConvert_CtoI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConvert_CtoI1ActionPerformed
        double m;
        double ft;
        String input = TextField01.getText().trim();
        if (!input.isEmpty()) {
            m = Double.parseDouble(input);
            ft = m * 3.281;
            String output = String.valueOf(ft);
            TextField02.setText(output);
        }
    }//GEN-LAST:event_ButtonConvert_CtoI1ActionPerformed

    private void Button_Close_CtoI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Close_CtoI1ActionPerformed
        TextField2.setText("");
        TextField3.setText("");
        Dialog_CtoII.dispose();
    }//GEN-LAST:event_Button_Close_CtoI1ActionPerformed

    private void ButtonConvert_CtoI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConvert_CtoI2ActionPerformed
        double km;
        double mi;
        String input = TextField01.getText().trim();
        if (!input.isEmpty()) {
            km = Double.parseDouble(input);
            mi = km / 1.609;
            String output = String.valueOf(mi);
            TextField02.setText(output);
        }
    }//GEN-LAST:event_ButtonConvert_CtoI2ActionPerformed

    private void Button_Close_CtoI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Close_CtoI2ActionPerformed
        TextField4.setText("");
        TextField5.setText("");
        Dialog_CtoIII.dispose();
    }//GEN-LAST:event_Button_Close_CtoI2ActionPerformed

    private void ButtonConvert_CtoI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConvert_CtoI3ActionPerformed
        double gr;
        double oz;
        String input = TextField01.getText().trim();
        if (!input.isEmpty()) {
            gr = Double.parseDouble(input);
            oz = gr /28.35;
            String output = String.valueOf(oz);
            TextField02.setText(output);
        }
    }//GEN-LAST:event_ButtonConvert_CtoI3ActionPerformed

    private void Button_Close_CtoI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Close_CtoI3ActionPerformed
        TextField6.setText("");
        TextField7.setText("");
        Dialog_CtoIV.dispose();
    }//GEN-LAST:event_Button_Close_CtoI3ActionPerformed

    private void ButtonConvert_CtoI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConvert_CtoI4ActionPerformed
        double kg;
        double pd;
        String input = TextField01.getText().trim();
        if (!input.isEmpty()) {
            kg = Double.parseDouble(input);
            pd = kg * 2.205;
            String output = String.valueOf(pd);
            TextField02.setText(output);
        }
    }//GEN-LAST:event_ButtonConvert_CtoI4ActionPerformed

    private void Button_Close_CtoI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Close_CtoI4ActionPerformed
        TextField8.setText("");
        TextField9.setText("");
        Dialog_CtoV.dispose();
    }//GEN-LAST:event_Button_Close_CtoI4ActionPerformed

    private void ButtonConvert_CtoI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConvert_CtoI5ActionPerformed
        double C;
        double F;
        String input = TextField01.getText().trim();
        if (!input.isEmpty()) {
            C = Double.parseDouble(input);
            F = (C * (9/5)) + 32;
            String output = String.valueOf(F);
            TextField02.setText(output);
        }
    }//GEN-LAST:event_ButtonConvert_CtoI5ActionPerformed

    private void Button_Close_CtoI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Close_CtoI5ActionPerformed
        TextField10.setText("");
        TextField11.setText("");
        Dialog_CtoVI.dispose();
    }//GEN-LAST:event_Button_Close_CtoI5ActionPerformed

    private void ButtonConvert_CtoI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConvert_CtoI6ActionPerformed
        double C;
        double K;
        String input = TextField01.getText().trim();
        if (!input.isEmpty()) {
            C = Double.parseDouble(input);
            K = C +273.15;
            String output = String.valueOf(K);
            TextField02.setText(output);
        }
    }//GEN-LAST:event_ButtonConvert_CtoI6ActionPerformed

    private void Button_Close_CtoI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Close_CtoI6ActionPerformed
       TextField12.setText("");
        TextField13.setText("");
        Dialog_CtoVII.dispose();
    }//GEN-LAST:event_Button_Close_CtoI6ActionPerformed

    private void KtoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KtoMActionPerformed
        Dialog_CtoIII.setVisible(true);
    }//GEN-LAST:event_KtoMActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Dialog_CtoIV.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Dialog_CtoV.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Dialog_CtoVI.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Dialog_CtoVII.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P14_JMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JButton ButtonConvert_CtoI;
    private javax.swing.JButton ButtonConvert_CtoI1;
    private javax.swing.JButton ButtonConvert_CtoI2;
    private javax.swing.JButton ButtonConvert_CtoI3;
    private javax.swing.JButton ButtonConvert_CtoI4;
    private javax.swing.JButton ButtonConvert_CtoI5;
    private javax.swing.JButton ButtonConvert_CtoI6;
    private javax.swing.JButton Button_Close_CtoI;
    private javax.swing.JButton Button_Close_CtoI1;
    private javax.swing.JButton Button_Close_CtoI2;
    private javax.swing.JButton Button_Close_CtoI3;
    private javax.swing.JButton Button_Close_CtoI4;
    private javax.swing.JButton Button_Close_CtoI5;
    private javax.swing.JButton Button_Close_CtoI6;
    private javax.swing.JMenu Converter;
    private javax.swing.JMenuItem CtoI;
    private javax.swing.JDialog Dialog_CtoI;
    private javax.swing.JDialog Dialog_CtoII;
    private javax.swing.JDialog Dialog_CtoIII;
    private javax.swing.JDialog Dialog_CtoIV;
    private javax.swing.JDialog Dialog_CtoV;
    private javax.swing.JDialog Dialog_CtoVI;
    private javax.swing.JDialog Dialog_CtoVII;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem KtoM;
    private javax.swing.JLabel Label01;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label12;
    private javax.swing.JLabel Label13;
    private javax.swing.JLabel Label14;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JMenu Lenght;
    private javax.swing.JMenu Mass;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MtoF;
    private javax.swing.JMenuItem Salute;
    private javax.swing.JPopupMenu.Separator Separator1;
    private javax.swing.JMenu Temperature;
    private javax.swing.JTextField TextField01;
    private javax.swing.JTextField TextField02;
    private javax.swing.JTextField TextField10;
    private javax.swing.JTextField TextField11;
    private javax.swing.JTextField TextField12;
    private javax.swing.JTextField TextField13;
    private javax.swing.JTextField TextField2;
    private javax.swing.JTextField TextField3;
    private javax.swing.JTextField TextField4;
    private javax.swing.JTextField TextField5;
    private javax.swing.JTextField TextField6;
    private javax.swing.JTextField TextField7;
    private javax.swing.JTextField TextField8;
    private javax.swing.JTextField TextField9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables

    private void setLooknFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P14_JMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

}
