/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UNIDAD_1_PA;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class P3_JOPTIONPANE extends javax.swing.JFrame {

    /**
     * Creates new form P3_JOPTIONPANE
     */
    public P3_JOPTIONPANE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        int result = 0;
        String message = "Do you really want to exit?";
        String title = "JOptionPane - ConfirmDialog";
        result = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        switch (result) {
            case JOptionPane.YES_OPTION:
                System.out.println("YES pressed!");
                break;
            case JOptionPane.NO_OPTION:
                System.out.println("NO pressed!");
                break;
        }
        // showInputDialog 
        message = "Type your name, please.";
        title = "JOptionPane - InputDialog";
        String name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
        switch (name.length()) {
            case 0:
                System.out.println("Unknown");
                break;
            default:
                System.out.println("Hello " + name + "!");
                break;
        }
        Object[] state = {"Single", "Married", "Widower", "Divorced"};
        Object iniState = "Single";
        message = "Select an option, please.";
        ImageIcon icon = new ImageIcon("\\Recursos\\shipit.png");
        String cState = (String) JOptionPane.showInputDialog(null, message, title, JOptionPane.WARNING_MESSAGE, icon, state, iniState);
        System.out.println("Option selected: " + cState);

        // showMessageDialog 
        message = "Your name is " + name + " and you are " + cState;
        title = "JoptionPane - MessageDialog";
        JOptionPane.showMessageDialog(null, message, title,
                JOptionPane.WARNING_MESSAGE);

        // showOptionDialog 
        message = "Good bye engineers!";
        title = "JOptionPane - OptionDialog";
        icon = null;
        Object[] options = {"Yes", "No", "Cancel"};
        Object iniOp = "Yes";
        int selected = JOptionPane.showOptionDialog(null, message, title, JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE, icon, options, iniOp);
        switch (selected) {
            case JOptionPane.YES_OPTION:
                System.out.println("Yes pressed.");
                break;
            case JOptionPane.NO_OPTION:
                System.out.println("No pressed.");
                break;
            case JOptionPane.CANCEL_OPTION:
                System.out.println("Cancel pressed.");
                break;
            case JOptionPane.CLOSED_OPTION:
                System.out.println("Close pressed.");
                break;

        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
}
