/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UNIDAD_1_PA;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Pheler
 */
public class P4_JOPTIONPANE extends javax.swing.JFrame {

    /**
     * Creates new form P4_JOPTIONPANE
     */
    public P4_JOPTIONPANE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String title, message, name;
        int mayor = 0, menor = 0, sum = 0, prom = 0, op=0, minimo, maximo;
        float sumatoriaopc = 0, de = 0, mediana = 0;
        title = "Introducir Tamaño - Operaciones";
        message = "Introduzca el Tamaño de los numeros a Generar: ";
        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
        int tamaño = Integer.parseInt(name);
        int[] array = new int[tamaño];
        Random rnd = new Random();
        System.out.println("Numeros Generados:");
        do {
            title = "Introducir Numeros - Operaciones";
            message = "Introduzca el rango Minimo de los numeros a Generar: ";
            name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
            minimo = Integer.parseInt(name);
            message = "Introduzca el rango Maximo de los numeros a Generar: ";
            name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
            maximo = Integer.parseInt(name);
            for (int i = 0; i < array.length; i++) {
                array[i]=rnd.nextInt((maximo-minimo)+1)+minimo;
                if (i < array.length - 1) {
                    System.out.print(array[i] + " - ");
                } else {
                    System.out.println(array[array.length - 1]);
                }
                //Sumatoria Total
                sum += array[i];
                //Mayor y Menor
                if (i == 0) {
                    mayor = array[i];
                    menor = array[i];
                } else if (array[i] > mayor) {
                    mayor = array[i];
                } else if (array[i] < menor) {
                    menor = array[i];
                }
            }
            //promedio
            prom = sum / tamaño;
            //Mediana
            int aux, j;
            for (int p = 1; p < array.length; p++) {
                aux = array[p];
                j = p - 1;
                while ((j >= 0) && (aux < array[j])) {
                    array[j + 1] = array[j];
                    j--;
                }
                array[j + 1] = aux;
            }
            System.out.println("");
            System.out.println("Serie de numeros Ordenados");
            for (int i = 0; i < array.length - 1; i++) {
                System.out.print(array[i] + " - ");
            }
            System.out.println(array[array.length - 1]);
            mediana = (array[4] + array[5]) / 2;
            message = "Numero Mayor:            " + mayor
                    + "\nNumero Menor:            " + menor
                    + "\nSumatoria Total:          " + sum
                    + "\nPromedio:                     " + prom
                    + "\nMediana:                        " + mediana;
            title = "Resultados - Operaciones";
            JOptionPane.showMessageDialog(null, message, title, JOptionPane.WARNING_MESSAGE);
            message = "Desea Volver a Ejecutar el Progama?";
            title = "|Reinicar - Operaciones|";
            int result = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            switch (result) {
                case JOptionPane.YES_OPTION:
                    System.out.println("YES pressed!");
                    op=1;
                    break;
                    
                case JOptionPane.NO_OPTION:
                    System.out.println("NO pressed!");
                    op = 0;
                    break;
            }
        } while (op==1);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
