/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UNIDAD_1_PA;

import javax.swing.JOptionPane;

/**
 *
 * @author Pheler
 */
public class P5_JOPTIONPANE extends javax.swing.JFrame {

    /**
     * Creates new form P5_JOPTIONPANE
     */
    public P5_JOPTIONPANE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        int op = 1, opp = 0, B, b, h, D, d, p, a, pi, r;
        float area = 0;
        String figura = "", message, title, name;
        do {
            title = "|Elección - Figuras Geometricas|";
            Object[] state = {"Cuadrado", "Rectangulo", "Triangulo", "Circulo", "Trapecio", "Rombo", "Pentagono", "Hexagono", "Octagono"};
            Object iniState = "Cuadrado";
            message = "Selecciona una opcion por favor.:";
            String cState = (String) JOptionPane.showInputDialog(null, message, title, JOptionPane.WARNING_MESSAGE, null, state, iniState);
            System.out.println("Opcion Seleccionada: " + cState);
            title = "|Datos - Figuras Geometricas|";
            if (null != cState) {
                switch (cState) {
                    case "Cuadrado":
                        figura = "Cuadrado";
                        message = "Introduzca en m, el valor de uno de los lados del Cuadrado: ";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        area = Integer.parseInt(name) * Integer.parseInt(name);
                        break;
                    case "Rectangulo":
                        figura = "Rectangulo";
                        message = "Introduzca en m, el valor de la base del Rectangulo: ";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        b = Integer.parseInt(name);
                        message = "Introduzca en m, el valor de la altura del Rectangulo: ";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        h = Integer.parseInt(name);
                        area = b * h;
                        break;
                    case "Triangulo":
                        figura = "Triangulo";
                        message = "Introduzca en m, el valor de la base del Triangulo: ";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        b = Integer.parseInt(name);
                        message = "Introduzca en m, el valor de la altura del Triangulo: ";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        h = Integer.parseInt(name);
                        area = (b * h) / 2;
                        break;
                    case "Circulo":
                        figura = "Circulo";
                        message = "Introduzca en m, el valor del radio del Circulo: ";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        r = Integer.parseInt(name);
                        area = (float) (3.14159 * Math.pow(r, 2));
                        break;
                    case "Trapecio":
                        figura = "Trapecio";
                        message = "Introduzca en m, el valor de la base menor del Trapecio: ";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        b = Integer.parseInt(name);
                        message = "Introduzca en m, el valor de la base mayor del Trapecio: ";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        B = Integer.parseInt(name);
                        message = "Introduzca en m, el valor de la altura del Trapecio: ";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        h = Integer.parseInt(name);
                        area = ((B + b) * h) / 2;
                        break;
                    case "Rombo":
                        figura = "Rombo";
                        message = "Introduzca en m, el valor de la Diagonal menor del Rombo: ";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        d = Integer.parseInt(name);
                        message = "Introduzca en m, el valor de la Diagonal mayor del Rombo: ";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        D = Integer.parseInt(name);
                        area = (D * d) / 2;
                        break;
                    case "Pentagono" :
                    case "Hexagono": 
                    case "Octagono":
                        switch (cState) {
                        case "Pentagono":
                            figura = "Pentágono";
                            break;
                        case "Hexagono":
                            figura = "Hexágono";
                            break;
                        default:
                            figura = "Octágono";
                            break;
                    }
                        message = "Introduzca en m, el valor del Perimetro del " + figura + " :";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        p = Integer.parseInt(name);
                        message = "Introduzca en m, el valor de la Apotema del " + figura + " :";
                        name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                        a = Integer.parseInt(name);
                        area = (p * a) / 2;
                        break;
                    default:
                        throw new AssertionError();
                }
            }
            message = "El Area del " + figura + " es de: " + area + "m2";
            title = "Resultados - Operaciones";
            JOptionPane.showMessageDialog(null, message, title, JOptionPane.WARNING_MESSAGE);
            message = "Desea Volver a Ejecutar el Progama?";
            title = "|Reinicar - Operaciones|";
            int result = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            switch (result) {
                case JOptionPane.YES_OPTION:
                    System.out.println("YES pressed!");
                    break;
                case JOptionPane.NO_OPTION:
                    System.out.println("NO pressed!");
                    op = 0;
                    break;
            }
        } while (op == 1);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
