/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UNIDAD_1_PA;

import javax.swing.JOptionPane;

/**
 *
 * @author Pheler
 */
public class P6_JOPTIONPANE extends javax.swing.JFrame {

    /**
     * Creates new form P6_JOPTIONPANE
     */
    public P6_JOPTIONPANE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        int op = 1, opp=0, Ab, h, D, d, p, a, pi, r;
        float volumen = 0;
        String cuerpo = "", message, title, name;
        do {
            title = "|Elección - Figuras Geometricas|";
            Object[] state = {"Cubo", "Prisma Rectangular", "Cilindro", "Piramide", "Cono", "Esfera"};
            Object iniState = "Cubo";
            message = "Selecciona una opcion por favor.:";
            String cState = (String) JOptionPane.showInputDialog(null, message, title, JOptionPane.WARNING_MESSAGE, null, state, iniState);
            System.out.println("Opcion Seleccionada: " + cState);
            if ("Cubo".equals(cState)) {
                opp = 1;
                cuerpo = "Cubo";
            } else if ("Prisma Rectangular".equals(cState)) {
                opp = 2;
                cuerpo = "Prisma Rectangular";
            } else if ("Cilindro".equals(cState)) {
                opp = 3;
                cuerpo = "Cilindro";
            } else if ("Piramide".equals(cState)) {
                opp = 4;
                cuerpo = "Piramide";
            } else if ("Trapecio".equals(cState)) {
                opp = 5;
                cuerpo = "Cono";
            } else if ("Cono".equals(cState)) {
                opp = 6;
                cuerpo = "Esfera";
            }
            title = "|Datos - Figuras Geometricas|";
            switch (opp) {
                case 1:
                    message = "Introduzca en m2, el valor de uno de los lados del Cubo: ";
                    name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                    volumen = (float) Math.pow(Integer.parseInt(name), 2);
                    break;
                case 2:
                    message = "Introduzca en m2, el valor de uno de los lados de la base del Prisma Rectangular: ";
                    name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                    Ab = Integer.parseInt(name);
                    message = "Introduzca en m2, el valor de la altura del Prisma Rectangular: ";
                    name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                    h = Integer.parseInt(name);
                    volumen = Ab * h;
                    break;
                case 3:
                    message = "Introduzca en m2, el valor de la altura del Cilindro: ";
                    name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                    h = Integer.parseInt(name);
                    message = "Introduzca en m2, el valor del radio de la base del Cilindro: ";
                    name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                    r = Integer.parseInt(name);
                    volumen = ((float) (3.14159 * Math.pow(r, 2)))*h;
                    break;
                case 4:
                    message = "Introduzca en m2, el valor de uno de los lados de la base de la Piramide: ";
                    name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                    Ab = Integer.parseInt(name);
                    message = "Introduzca en m2, el valor de la altura de la Piramide: ";
                    name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                    h = Integer.parseInt(name);
                    volumen = (Ab * h)/3;
                    break;
                case 5:
                    message = "Introduzca en m2, el valor de la altura del Cono: ";
                    name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                    h = Integer.parseInt(name);
                    message = "Introduzca en m2, el valor del radio de la base del Cono: ";
                    name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                    r = Integer.parseInt(name);
                    volumen = (float) (3.14159 * Math.pow(r, 2)*h)/3;
                    break;
                case 6:
                    message = "Introduzca en m2, el valor del radio de la Esfera: ";
                    name = JOptionPane.showInputDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
                    r = Integer.parseInt(name);
                    volumen = (float) (3/4*3.14159*Math.pow(r, 3));
                    break;
                default:
                    throw new AssertionError();
            }
            message = "El Volumen del " + cuerpo + " es de: " + volumen + "m3";
            title = "Resultados - Operaciones";
            JOptionPane.showMessageDialog(null, message, title, JOptionPane.WARNING_MESSAGE);
            message = "Desea Volver a Ejecutar el Progama?";
            title = "|Reinicar - Operaciones|";
            int result = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            switch (result) {
                case JOptionPane.YES_OPTION:
                    System.out.println("YES pressed!");
                    break;
                case JOptionPane.NO_OPTION:
                    System.out.println("NO pressed!");
                    op = 0;
                    break;
            }
        } while (op==1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
