package UNIDAD_1_PA;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author GuillermoToledano
 */
public class P8_JButton extends javax.swing.JFrame {

    /**
     * Creates new form P8_JButton
     */
    ImageIcon lock = new ImageIcon("src/Recursos/Locked-icon.png");
    ImageIcon unlock = new ImageIcon("src/Recursos/Unlocked-icon.png");
    public P8_JButton() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        Button04.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label01 = new javax.swing.JLabel();
        Button05 = new javax.swing.JButton();
        Label02 = new javax.swing.JLabel();
        ToggleButton01 = new javax.swing.JToggleButton();
        Button02 = new javax.swing.JButton();
        Button01 = new javax.swing.JButton();
        Button03 = new javax.swing.JButton();
        Button06 = new javax.swing.JButton();
        Button04 = new javax.swing.JButton();
        Button07 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JButton");
        setMinimumSize(new java.awt.Dimension(300, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 300));

        Label01.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label01.setText("Color selector");

        Button05.setText("Reset");
        Button05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button05ActionPerformed(evt);
            }
        });

        ToggleButton01.setSelected(true);
        ToggleButton01.setText("Lock");
        ToggleButton01.setDoubleBuffered(true);
        ToggleButton01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToggleButton01MouseClicked(evt);
            }
        });

        Button02.setText("Green");
        Button02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button02ActionPerformed(evt);
            }
        });

        Button01.setText("Red");
        Button01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button01ActionPerformed(evt);
            }
        });

        Button03.setText("Blue");
        Button03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button03ActionPerformed(evt);
            }
        });

        Button06.setText("Disable");
        Button06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button06ActionPerformed(evt);
            }
        });

        Button04.setText("Enable");
        Button04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button04ActionPerformed(evt);
            }
        });

        Button07.setText("Exit");
        Button07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button07ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ToggleButton01, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label02, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button07)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label01, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Button01, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button04, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button02, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button03, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button05, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button06, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Button01, Button02, Button03, Button04, Button05, Button06});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Button07, ToggleButton01});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Label01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button02)
                    .addComponent(Button01)
                    .addComponent(Button03))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button05)
                    .addComponent(Button06)
                    .addComponent(Button04))
                .addGap(11, 11, 11)
                .addComponent(Label02, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToggleButton01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(Button07)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Button01, Button02, Button03, Button04, Button05, Button06});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Button07, ToggleButton01});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button05ActionPerformed
        this.getContentPane().setBackground(Color.WHITE);
        Label01.setForeground(Color.BLACK);
        Label01.setText("Color selector");
        System.out.println("Reset selected!");
        System.out.println("Action Command: " + evt.getActionCommand());
    }//GEN-LAST:event_Button05ActionPerformed

    private void ToggleButton01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToggleButton01MouseClicked
        boolean selected = ToggleButton01.isSelected();
        if (selected) {
            System.out.println("Button state: " + selected);
            Label02.setIcon(lock);
            ToggleButton01.setText("Unlock");
        } else {
            System.out.println("Button state: " + selected);
            Label02.setIcon(unlock);
            ToggleButton01.setText("Lock");
        }
    }//GEN-LAST:event_ToggleButton01MouseClicked

    private void Button02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button02ActionPerformed
        this.getContentPane().setBackground(Color.GREEN);
        Label01.setForeground(Color.WHITE);
        Label01.setText("Green Selected");
    }//GEN-LAST:event_Button02ActionPerformed

    private void Button01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button01ActionPerformed
        this.getContentPane().setBackground(Color.RED);
        Label01.setForeground(Color.WHITE);
        Label01.setText("Red Selected");
    }//GEN-LAST:event_Button01ActionPerformed

    private void Button03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button03ActionPerformed
        this.getContentPane().setBackground(Color.BLUE);
        Label01.setForeground(Color.WHITE);
        Label01.setText("Blue Selected");
    }//GEN-LAST:event_Button03ActionPerformed

    private void Button06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button06ActionPerformed
        Button01.setEnabled(false);
        Button02.setEnabled(false);
        Button03.setEnabled(false);
        Button04.setEnabled(true);
        Button06.setEnabled(false);
        System.out.println("Optione Selected: " + Button06.getText());
    }//GEN-LAST:event_Button06ActionPerformed

    private void Button04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button04ActionPerformed
        Button01.setEnabled(true);
        Button02.setEnabled(true);
        Button03.setEnabled(true);
        Button04.setEnabled(false);
        Button06.setEnabled(true);
        System.out.println("Optione Selected: " + Button04.getText());
    }//GEN-LAST:event_Button04ActionPerformed

    private void Button07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button07ActionPerformed
        String message = "Are you sure?";
        String title = "Select an option";
        int opt = JOptionPane.showConfirmDialog(this, message, title, 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {
            message = "See you later!";
            JOptionPane.showMessageDialog(this, message, "",
            JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_Button07ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P8_JButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P8_JButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P8_JButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P8_JButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new P8_JButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button01;
    private javax.swing.JButton Button02;
    private javax.swing.JButton Button03;
    private javax.swing.JButton Button04;
    private javax.swing.JButton Button05;
    private javax.swing.JButton Button06;
    private javax.swing.JButton Button07;
    private javax.swing.JLabel Label01;
    private javax.swing.JLabel Label02;
    private javax.swing.JToggleButton ToggleButton01;
    // End of variables declaration//GEN-END:variables
}
